### PR TITLE
Reorganize the package after the pattern of ocaml-unix-(dirent|sys-stat|fcntl|&c.)

### PR DESCRIPTION
**Pull request by yallop**

### CODE REVIEW

**Comment by yallop** [comment]
Main organizational changes:
* Use `ocamlbuild` in place of custom Makefile rules
* Reorder the directories; in place of
  ```
  lib/
      ctypes/
      no-ctypes/
      lwt/
      no-lwt/
  ```
  we now have
  ```
  lib/
  unix/
  ```
* Rework the module namespace.  In place of a single module `Unix_unistd` whose signature varies depending on which packages are installed, we now have three separate modules whose availability depends on which packages are installed
  - `Unistd` (always available).
  - `Unistd_unix` (available if `unix-type-representations` and `ctypes` are available)
  - `Unistd_unix_lwt` (available if the dependencies of `Unistd_unix` and the `lwt` package are available)
* Rework the interface:
  - The `Unistd_unix_lwt` is now a straightforward module with four functions, not a functor
  - Functions in the `Unistd_unix_lwt` module no longer have the `_lwt` suffix 
* The `META` file is no longer auto-generated
* The C stubs are now split across more files: the parts which are not `Unix`-dependent are in `lib/unistd_stubs.c`, while the `Unix`-dependent parts are in `unix/unix_unistd_stubs.c`.

**Comment by yallop** [comment]
I'll rebase on #13 once that's merged.

**Comment by dsheets** [comment]
Perhaps we should depend on `base-unix` too? (I know it is transitive for `unix-type-representations`.)

**Comment by dsheets** [comment]
Also, I think usually all the stubs are `Unix` dependent and there is not a `lib/unistd_stubs.c` file but there may be a `_util.c` file. What split stubs are you thinking of?

**Comment by yallop** [comment]
> I'll rebase on #13 once that's merged.

I've rebased on #13.

**Comment by yallop** [comment]
> Also, I think usually all the stubs are Unix dependent and there is not a lib/unistd_stubs.c file but there may be a _util.c file. What split stubs are you thinking of?

There are some [stubs](https://github.com/dsheets/ocaml-unix-unistd/blob/081ad988f13d1665431f6bcc7fadc10225e2832e/lib/unix_unistd_common.ml#L21-L24) used in what is currently (i.e. in `master`) called `Unix_unistd_common` for retrieving constant values:

```ocaml
  external r_ok : unit -> int = "unix_unistd_r_ok" "noalloc"
  external w_ok : unit -> int = "unix_unistd_w_ok" "noalloc"
  external x_ok : unit -> int = "unix_unistd_x_ok" "noalloc"
  external f_ok : unit -> int = "unix_unistd_f_ok" "noalloc"
```

**Comment by yallop** [comment]
> Perhaps we should depend on base-unix too?

Yes.  I'll add a dependency.

**Comment by yallop** [comment]
>>  Perhaps we should depend on base-unix too?

> Yes. I'll add a dependency.

See df0abb7.

**Comment by dsheets** [comment]
Ok, I think those stubs should be moved into a type detection stage like the other constants. In the case of the `SEEK` flags that are not cross-platform they can be put in `unix/unix_unistd_util.c` like in `fcntl`.

This was all written before we had ctypes stub gen so the constant stubs were necessary.

**Comment by yallop** [comment]
I've added a constant-binding stage in 6bde883, which also makes corresponding changes to the interface:
  * There's now a `Host` module in each of `Unistd.Access`, `Unistd.Seek` and `Unistd.Sysconf` with conversion functions `to_defns` and `from_defns` in place of the `host` type
  * The `host` values have been moved to `Unistd_unix`

For detecting the non-portable `SEEK` flags I've added some `#ifdef` checks to the code that's prepended to the file generated by Ctypes.

**Comment by dsheets** [comment]
Thanks!

**Pull request merged**
